Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [7]:
# Ans 1. Creating 1D array and performing operations on it
import numpy as np
a=np.array([0,1,2,3,4])
print(f"Original array is: {a}")
print(f"(a) Adding of 2 in all elements {a+2}")
print(f"(b) Multiplying 3 with all elements {a*3}")
print(f"(c) Dividing every element by 2 {a/2.0}")

Original array is: [0 1 2 3 4]
(a) Adding of 2 in all elements [2 3 4 5 6]
(b) Multiplying 3 with all elements [ 0  3  6  9 12]
(c) Dividing every element by 2 [0.  0.5 1.  1.5 2. ]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
# Ans 2. Basic NumPy array 
arr=np.array([1, 2, 3, 6, 4, 5])
print(f"Original array is: {arr}")
print(f"(a) Reversed array is: {np.flip(arr)}")
x=np.array([1,2,3,4,5,1,2,1,1,1])
maxX=np.bincount(x)
maximum=max(maxX)
print(f"(b) \n\t(i) Most frequent element(s) in {x} is(are) :")
for i in range(len(maxX)):
    if maxX[i] == maximum:
        indices = np.where(x == i)[0]
        print(f"\tElement {i}, appearing {maximum} times at indices {indices.tolist()}")
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
maxX=np.bincount(y)
maximum=max(maxX)

print(f"\t(ii) Most frequent element(s) in {y} is(are) :")
for i in range(len(maxX)):
    if maxX[i] == maximum:
        indices = np.where(y == i)[0] 
        print(f"\tElement {i}, appearing {maximum} times at indices {indices.tolist()}")

Original array is: [1 2 3 6 4 5]
(a) Reversed array is: [5 4 6 3 2 1]
(b) 
	(i) Most frequent element(s) in [1 2 3 4 5 1 2 1 1 1] is(are) :
	Element 1, appearing 5 times at indices [0, 5, 7, 8, 9]
	(ii) Most frequent element(s) in [1 1 1 2 3 4 2 4 3 3] is(are) :
	Element 1, appearing 3 times at indices [0, 1, 2]
	Element 3, appearing 3 times at indices [4, 8, 9]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [19]:
# ANS 3.

import numpy as np
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])


print(f"(a) Element at 1st row, 2nd column: {arr[0, 1]}")

print(f"(b) Element at 3rd row, 1st column: {arr[2, 0]}")


(a) Element at 1st row, 2nd column: 20
(b) Element at 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [1]:
# ANS 4.

import numpy as np
Ashpreet = np.linspace(10, 100, 25)

print("Array:", Ashpreet)
print("Dimensions:", Ashpreet.ndim)
print("Shape:", Ashpreet.shape)
print("Total elements:", Ashpreet.size)
print("Data type of each element:", Ashpreet.dtype)
print("Total bytes consumed:", Ashpreet.nbytes)


Ashpreet_transpose = Ashpreet.reshape(25, 1)
print("\nTranspose using reshape():\n", Ashpreet_transpose)

Ashpreet_T = Ashpreet.T
print("\nTranspose using T attribute:\n", Ashpreet_T)

print("\nNo, we cannot use the T attribute for a 1D array to get a column vector.")
print("T attribute only swaps axes and has no effect on a 1D array.")


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type of each element: float64
Total bytes consumed: 200

Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

No, we cannot use the T attribute for a 1D array to get a column vector.
T attribute only swaps axes and has no effect on a 1D array.


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [23]:
# ANS 5.


import numpy as np
ucs420_Ashpreet = np.array([[10, 20, 30, 40],
                           [50, 60, 70, 80],
                           [90, 15, 20, 35]])

mean_value = np.mean(ucs420_Ashpreet)
median_value = np.median(ucs420_Ashpreet)
max_value = np.max(ucs420_Ashpreet)
min_value = np.min(ucs420_Ashpreet)
unique_elements = np.unique(ucs420_Ashpreet)

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique elements:", unique_elements)

reshaped_ucs420_Ashpreet = ucs420_Ashpreet.reshape(4, 3)
print("\nReshaped array (4x3):\n", reshaped_ucs420_Ashpreet)

resized_ucs420_Ashpreet = np.resize(ucs420_Ashpreet, (2, 3))
print("\nResized array (2x3):\n", resized_ucs420_Ashpreet)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2x3):
 [[10 20 30]
 [40 50 60]]
